name = input("Enter a name: ")
age = int(input("Enter age: "))
section = input("Enter Section: ")
grp = input("Enter Group: ")
gpa = float(input("Enter GPA: "))
classs = int(input("Enter your class: "))
'''print("our new students name is "+name)
print(name+" lives in Dhaka")
print(name +" reads in class 12")'''
print("Student Information")
print("----------------------")
print("Student's Name: "+name)
print("Student's Age : ",age,)
print("Class : ",classs,)
print("Group : "+grp)
print("Section : "+section)
print("GPA : ",gpa,)